// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKmJ7zy59iBBa5pQM9SRtw9JgSL-kNPs',
    appId: '1:867444863625:web:dc145615d737ca81660c58',
    messagingSenderId: '867444863625',
    projectId: 'desaster-relief-v2',
    authDomain: 'desaster-relief-v2.firebaseapp.com',
    storageBucket: 'desaster-relief-v2.appspot.com',
    measurementId: 'G-6LJXJLJ5N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxRqL4mHrh9d8QmDOw-3NAFwbuIjdDt4',
    appId: '1:867444863625:android:575bbb2d2a157b03660c58',
    messagingSenderId: '867444863625',
    projectId: 'desaster-relief-v2',
    storageBucket: 'desaster-relief-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutyFL2uAGhadadkBLatDLSB_1IdMatHA',
    appId: '1:867444863625:ios:7b0066f0f4aa7293660c58',
    messagingSenderId: '867444863625',
    projectId: 'desaster-relief-v2',
    storageBucket: 'desaster-relief-v2.appspot.com',
    iosClientId: '867444863625-ik2c8l421tci5bea0jelbpq0jhf0g36o.apps.googleusercontent.com',
    iosBundleId: 'com.example.disasterReliefV2',
  );
}
